services:
  back:
    container_name: back
    image: back
    build:
      context: ./back
      dockerfile: Dockerfile
    working_dir : /usr/src/app
    ports:
      - 3000:3000
    env_file: ../.env
    volumes: 
      - back_vol:/usr/src/app
      - sqlite_data:/data
    networks:
      - transcendence
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  front:
    container_name: front
    image: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      back:
        condition: service_healthy
    env_file: ../.env
    volumes: 
      - front_vol:/usr/src/app
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge
    name: transcendence

volumes:
  back_vol: {}
  front_vol: {}
  sqlite_data: {}